project:
  type: website
  output-dir: docs

website:
  title: "gsipes2.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: tutorials.qmd
        text: Tutorials
      # NOTE: The order of items here defines the navbar order. Projects appears before Tutorials.

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



