name: quarto
channels:
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - pandoc
  - pip
  - python=3.12
  - quarto
  - ipykernel
  - jupyter
  - jupyter_client
  - pyyaml
  - pip:
    - absl-py==2.3.1
    - filelock==3.19.1
    - flatbuffers==25.2.10
    - fsspec==2025.9.0
    - jax==0.7.2
    - jaxlib==0.7.2
    - matplotlib==3.10.6
    - mediapipe==0.10.14
    - ml_dtypes==0.5.3
    - mpmath==1.3.0
    - munkres==1.1.4
    - networkx==3.5
    - numpy==2.2.6
    - opencv-contrib-python==4.12.0.88
    - opencv-python==4.12.0.88
    - polars==1.33.1
    - quarto-cli==1.8.24
    - scipy==1.16.2
    - sounddevice==0.5.2
    - sympy==1.14.0
    - torch==2.8.0
    - torchvision==0.23.0
    - ultralytics==8.3.202
    - ultralytics-thop==2.0.17
    - wheel==0.45.1
    - zstandard==0.25.0

